name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-build:
    name: Build & Dockerize Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build backend with Maven
        run: mvn clean install

      - name: Package backend
        run: mvn package

      - name: Build Docker image for backend
        run: docker build -t task1-backend:latest ./  # adjust path if needed

      - name: Docker login (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push backend Docker image to GHCR
        run: |
          docker tag task1-backend:latest ghcr.io/${{ github.repository_owner }}/task1-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/task1-backend:latest

  frontend-build:
    name: Build & Dockerize Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build Docker image for frontend
        run: docker build -t task3-frontend:latest ./  # adjust path if needed

      - name: Docker login (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push frontend Docker image to GHCR
        run: |
          docker tag task3-frontend:latest ghcr.io/${{ github.repository_owner }}/task3-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/task3-frontend:latest
